### ISSUE TITLE
PRACTICA 9_ DIAGRAMA DE SECUENCIA 

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo-ggar#1]
[PRACTICA 9_DIAGRAMA DE SECUENCIA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo-ggar/files/10199057/PRACTICA.9_DIAGRAMA.DE.SECUENCIA.pdf)

**Comment by Heidi-19** [comment]
50%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
